# Generated by Django 4.1.5 on 2023-02-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_inicio', models.IntegerField()),
                ('fecha_entrega', models.IntegerField()),
                ('entrega', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='alumnos',
            name='documento',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
